export const POST_KIND = {
    STRING: '',
    BOLD: '**',
    BLOCKQUOTE: '>',
    BREAK: 'br',
    CODE_INLINE: '`',
    CODE_FENCE: '```',
    HEADING_1: '#',
    HEADING_2: '##',
    HEADING_3: '###',
    HEADING_4: '####',
    HEADING_5: '#####',
    HEADING_6: '#######',
    IMAGE: 'img',
    ITALICS: '*',
    LINK: '[]',
    LIST_ITEM: 'li',
    LIST_ORDERED: 'ol',
    LIST_UNORDERED: 'ul',
    PARAGRAPH: 'p',
    STRIKE: '~',
    THEMATIC_BREAK: 'hr'
}